name: crypto-pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - requests
  - python-dotenv
  - psycopg2
  - black
  - pandas
  - pyarrow
  - pip
  - pip:
    - confluent-kafka[avro,schemaregistry]
    - minio